import SocketIoProvider from '@/providers/SocketContext/SocketIoProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { GlobalProvider } from '@/providers/GlobalContext/GlobalContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body suppressHydrationWarning={true} className={inter.className}>
				<GlobalProvider>
					<SocketIoProvider>{children}</SocketIoProvider>
				</GlobalProvider>
			</body>
		</html>
	)
}
